### PR TITLE
No longer throw error for the supported B2 provider

### PR DESCRIPTION
**Pull request by cbess**
Adds backblaze B2 to the `providers` list

### CODE REVIEW

**Comment by cbess** [comment]
@ItalyPaleAle Thanks for the library! It has really clean code and was exactly what I was looking for to help me use online storage services.

**Comment by cbess** [comment]
For anyone wanting a work around until this PR is merged, simply do:
```js
// TODO: remove once above PR has been merged
// replace/update the providers, due to missing value in the canonical array
SMCloudStore.Providers = () => ['backblaze-b2', 'generic-s3', 'aws-s3'];
```

**Comment by ItalyPaleAle** [comment]
Thanks for catching this! I've merged this into master and will release it soon.

**Comment by ItalyPaleAle** [comment]
Released version 0.2.1 with this fix.

**Pull request merged**
